# Dockerfile toolback
FROM ruby:3.2.0 as rails-toolbox

# Default directory
ENV INSTALL_PATH /opt/app
RUN mkdir -p $INSTALL_PATH

# Install rails
RUN gem install rails bundler

WORKDIR /opt/app

# Run a shell
CMD ["/bin/sh"]

