
version: 2.1
workflows:
  say-hello-workflow:
    jobs:
      - say-hello
  build:
    jobs:
      - build
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"
  build:
    working_directory: /blog
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      #- run:
          #name: Install dependencies
          #command: |
            #apk add --no-cache \
              #py-pip=9.0.0-r1
            #pip install \
              #docker-compose==1.12.0 \
              #awscli==1.11.76
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/blog.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/blog.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=blog -t blog .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/blog.tar blog
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/blog.tar
      #- run:
          #name: Run tests
          #command: |
            #docker-compose -f ./docker-compose.test.yml up
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_ACCESS_TOKEN
              docker tag app "pevanscfi/blog:${CIRCLE_SHA1}"
              docker push "pevanscfi/blog:${CIRCLE_SHA1}"
            fi

