version: 2.1
workflows:
  build:
    jobs:
      - build_and_push
      - promote:
          filters:
            branches:
              only:
                - main
          type: approval
          requires:
            - build_and_push
      - deploy:
          filters:
            branches:
              only:
                - main
          requires:
            - promote
jobs:
  build_and_push:
    machine: # executor type
      image: ubuntu-2004:202010-01
      docker_layer_caching: true
    steps:
      - checkout
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=blog -t blog .
      - run:
          name: Setup Code Climate test-reporter
          command: |
            sudo apt-get install jq
            curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
            chmod +x ./cc-test-reporter
      - run:
          name: Run cypress tests
          command: |
            mkdir coverage
            docker run -e "RAILS_ENV=test" blog bundle exec rake db:create db:migrate cypress:run
      - run:
          name: Run rspec tests
          command: |
            mkdir coverage
            docker run -v $(pwd)/coverage:/opt/app/coverage -e "RAILS_ENV=test" blog bundle exec rspec
      - run:
          name: Report test coverage
          command: |
            sed -i 's%\/opt\/app\/%%g' coverage/coverage.json
            ./cc-test-reporter format-coverage -t simplecov coverage/coverage.json
            ./cc-test-reporter upload-coverage
      - deploy:
          condition:
            - equal: [ main, << pipeline.git.branch >> ]
          name: Push application Docker image
          command: |
            docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_ACCESS_TOKEN
            docker tag blog "pevanscfi/blog:${CIRCLE_SHA1}"
            docker push "pevanscfi/blog:${CIRCLE_SHA1}"

  deploy:
    working_directory: /
    docker:
      - image: pevanscfi/ops-toolbox:latest
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ef:9b:5b:60:63:61:04:a9:52:32:e7:cd:0b:d7:a2:43"
      - run:
          name: Update the gitops repo
          command: |
            git config --global user.email "paul+circleci@wevans.io"
            git config --global user.name "CircleCI"
            git clone git@github.com:wevanscfi/homelab.git
            cd homelab
            yq e -i '(.spec.source.helm.parameters[] | select(.name == "image.tag")).value = "'"$CIRCLE_SHA1"'"' manifests/wevans/templates/blog.yaml
            git add manifests/wevans/templates/blog.yaml
            git commit -m "Deploy blog: ${CIRCLE_SHA1}"
            git push origin main

