
version: 2.1
workflows:
  build:
    jobs:
      - build
jobs:
  build:
    working_directory: /blog
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
          paths:
            - /caches/blog.tar
      - run:
          name: Load Docker image layer cache
          command: |
            set +o pipefail
            docker load -i /caches/blog.tar | true
      - run:
          name: Build application Docker image
          command: |
            docker build --cache-from=blog -t blog .
      - run:
          name: Save Docker image layer cache
          command: |
            mkdir -p /caches
            docker save -o /caches/blog.tar blog
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - /caches/blog.tar
      #- run:
          #name: Run tests
          #command: |
            #docker-compose -f ./docker-compose.test.yml up
      - deploy:
          name: Push application Docker image
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              docker login --username $DOCKER_HUB_USER --password $DOCKER_HUB_ACCESS_TOKEN
              docker tag blog "pevanscfi/blog:${CIRCLE_SHA1}"
              docker push "pevanscfi/blog:${CIRCLE_SHA1}"
            fi
  gitops:
    working_directory: /
    steps:
      - run:
          name: Checkout the gitops repo
          command: |
            if [ "${CIRCLE_BRANCH}" == "main" ]; then
              git clone https://github.com/wevanscfi/homelab.git
              cd homelab && ls -l
            fi

